# IPC Devices
#obj-y += platform_ipc.o
obj-$(subst m,y,$(CONFIG_MFD_INTEL_MSIC)) += platform_msic.o
obj-$(subst m,y,$(CONFIG_SND_MFLD_MACHINE)) += platform_msic_audio.o
obj-$(subst m,y,$(CONFIG_GPIO_MSIC)) += platform_msic_gpio.o
obj-$(subst m,y,$(CONFIG_MFD_INTEL_MSIC)) += platform_msic_ocd.o
obj-$(subst m,y,$(CONFIG_MFD_INTEL_MSIC)) += platform_msic_battery.o
obj-$(subst m,y,$(CONFIG_INTEL_MID_POWER_BUTTON)) += platform_msic_power_btn.o
obj-$(subst m,y,$(CONFIG_GPIO_INTEL_PMIC)) += platform_pmic_gpio.o
obj-$(subst m,y,$(CONFIG_INTEL_MFLD_THERMAL)) += platform_msic_thermal.o
obj-$(subst m,y,$(CONFIG_VLV2_PLAT_CLK)) += platform_vlv2_plat_clk.o
# I2C Devices
obj-$(subst m,y,$(CONFIG_SENSORS_EMC1403)) += platform_emc1403.o
obj-$(subst m,y,$(CONFIG_BATTERY_BQ27x00)) += platform_bq27500.o
#obj-$(subst m,y,$(CONFIG_SENSORS_LIS3LV02D)) += platform_lis331.o
obj-$(subst m,y,$(CONFIG_GPIO_PCA953X)) += platform_max7315.o
obj-$(subst m,y,$(CONFIG_INPUT_MPU3050)) += platform_mpu3050.o
obj-$(subst m,y,$(CONFIG_INPUT_BMA150)) += platform_bma023.o
obj-$(subst m,y,$(CONFIG_GPIO_PCA953X)) += platform_tca6416.o
obj-$(subst m,y,$(CONFIG_DRM_MEDFIELD)) += platform_tc35876x.o
# SPI Devices
obj-$(subst m,y,$(CONFIG_SERIAL_MRST_MAX3110)) += platform_max3111.o
# MISC Devices
#obj-$(subst m,y,$(CONFIG_KEYBOARD_GPIO)) += platform_gpio_keys.o
# WIFI devices
obj-$(subst m,y,$(CONFIG_MMC_SDHCI_ACPI)) += platform_sdio_regulator.o
obj-y += platform_iwlwifi.o
#SAR Sensor
obj-$(subst m,y,$(CONFIG_INPUT_SX9310)) += platform_sx9310.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_HIDEEP_IST940E)) += platform_ist940e.o
obj-$(subst m,y,$(CONFIG_LEDS_TPS61163A)) += platform_tps61163a.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_HIDEEP_IST771X)) += platform_ist771x.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_WACOM_I2C)) += platform_wacom.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_HIDEEP)) += platform_hideep.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_GT9XX)) += platform_gt9xx.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_MORGAN_I2C)) += platform_morgan.o
obj-$(subst m,y,$(CONFIG_INPUT_TI_2604L_HAPTICS)) += platform_haptics_2604l.o

