# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o

obj-$(CONFIG_SWITCH_ARIZONA)	+= switch-arizona.o
obj-y                           += hall_switch.o
obj-y                           += sec_hall_switch.o
obj-y                           += switch_slot_gpio.o

