#
# Makefile for the hideep drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_HIDEEP)   += hideep.o
hideep-objs := hideep_ts.o hideep_fw.o hideep_sysfs.o hideep_update.o hideep_swd.o hideep_Testmode.o hideep_iface.o
